### ISSUE TITLE
Needs tests

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/fewpjs-build-the-example#10]
I love the new JS sections. These look awesome!

But a number are lacking tests. This one in particular seems like a large benchmark for students bring the 3 pillars together. But it has only one test assertion, which allows incomplete submissions to be green (e.g. https://github.com/learn-co-students/fewpjs-build-the-example-v-000/pull/43/files ). 

More tests please!

**Comment by ihollander** [comment]
Hi @garettarrowood - sorry no one followed up on this! You can see my answer to a similar issue here if you're interested: https://github.com/learn-co-curriculum/fewpjs-build-the-example/issues/14#issuecomment-885870986
