### ISSUE TITLE
Solution code has a significant flaw

### ISSUE THREAD

**Issue by mkirby** [learn-co-curriculum/fewpjs-build-the-example#12]
Each article element in the lab's index.html file has an unordered list where the singular list item contains the following code:
```
<li class="like">Like! <span class="like-glyph">&#x2661;</span></li>
``` 
The solution code attempts to grab the articleHearts with the following code:
```
let articleHearts = document.querySelectorAll(".like");
```

and then add's event listeners to each entire list item element.
```
for (let glyph of articleHearts) {
  glyph.addEventListener("click", likeCallback);
}
```

The issue arises when the variable heart is assigned to the event.target in the likeCallback function. If the event target was the list item element and not the nested span element inside of that list item then the solution code will try to replace the list items innerText which then errors out and displays "undefined" (see screenshot).
```
function likeCallback(e) {
  let heart = e.target;
  mimicServerCall("bogusUrl")
    .then(function(serverMessage){
      heart.innerText = glyphStates[heart.innerText];
      heart.style.color = colorStates[heart.style.color];
    })
    .catch(function(error) {
      document.getElementById("modal").className = "";
    });
}
```
**No more functionality to Like! ♥!**

![Screen Shot 2020-10-29 at 5 52 58 PM](https://user-images.githubusercontent.com/8262355/97636920-30798000-1a10-11eb-892f-8d6682dff5d9.png)

I think the simplest solution is to grab all the articleHearts from the span class instead and that span will be the only element with a click event listener.
```
let articleHearts = document.querySelectorAll(".like-glyph");
```
and the style.css file should be updated to reflect the cursor change only when hovered over the span element with the .like-glyph class:
```
.like-glyph {
  cursor: pointer;
}
```

**Comment by lizbur10** [comment]
Hi there! Thanks for spotting this issue and providing feedback. The solution code and CSS file have been updated to fix this issue.

Thanks for contributing to the Flatiron School curriculum! 💙
