### ISSUE TITLE
why mimic?!

### ISSUE THREAD

**Issue by bolloland** [learn-co-curriculum/fewpjs-build-the-example#15]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/2620/assignments/76888?module_item_id=148432

## What should be changed?

there's too many pieces to the Mimic server call, have we ever seen this before?
Why can't this be built or defined elsewhere so we can GET PRACTICE WITH FETCH instead of trying to navigate around some mimic that has never been explained before. Very frustrating roadblock.

**Comment by lizbur10** [comment]
Hi there! Thanks for submitting this feedback, and apologies for the frustrations you encountered.

I have updated the Readme to add more explanation about the `mimicServerCall` function and clarify how it fits into the lab.  Please note, however, that these changes may not be reflected in your Canvas course.

Thanks for contributing to the Flatiron School curriculum! 💙
