### ISSUE TITLE
Use of custom mimicServerCall function instead of using a faked JSON API seems off topic

### ISSUE THREAD

**Issue by rossmawd** [learn-co-curriculum/fewpjs-build-the-example#3]
Hi,
Upto this point the labs have had us getting permanence with our data by using a 'faked' JSON api (json-server --watch db.json). This has allowed us to get used to dealing with Promises and Response objects etc. The mimicServerCall seems to break from giving us this practice and I'm not sure why...

**Comment by sgharms** [comment]
We do this to break you from pattern-matching: you'll have APIs like this (in iOS, in Web, in asynchronous back-end frameworks). We hope, in time, you'll appreciate this record-needle scratch moment of surprise.
