### ISSUE TITLE
A page not found 404 

### ISSUE THREAD

**Issue by MohammedAlMaqbli** [learn-co-curriculum/fewpjs-build-the-example#7]
Hi. I am a student with Recoded Sanaa, but the GitHub  link  provided to me returns a 404 page. Can you please help? This is the link in to the lab in learn.co : https://learn.co/tracks/re-coded-front-end-web-development-v2/javascript/pulling-it-all-together/build-the-example

**Comment by sgharms** [comment]
I'm not sure what's happening there @MohammedAlMaqbli. The lab's "official" link is this: https://github.com/learn-co-curriculum/fewpjs-build-the-example

If you can get there you can see the materials that Learn is using. It's also the repository where issues you report are created! That might be a tool to help you get back to the official repository when you need it.

Good luck!

Steven
