### ISSUE TITLE
Broken image - screenshot final

### ISSUE THREAD

**Issue by AudTheCodeWitch** [learn-co-curriculum/fewpjs-build-the-example#8]
The example screenshot image link is broken. If you open the image in a new tab, you get the following error:

`This site can’t be reached
curriculum-content.s3.amazonaws.com’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by sgharms** [comment]
I was unable to duplicate this issue:

![image](https://user-images.githubusercontent.com/50019/67503297-5f1e8700-f655-11e9-959f-5a63df0d517e.png)

That image is wide open, permissions wise.

![image](https://user-images.githubusercontent.com/50019/67503421-9b51e780-f655-11e9-8fe3-645dfc85b0a9.png)


The error suggests a network error.This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
